### ISSUE TITLE
Time is showing in local time instead of time in DR

### ISSUE THREAD

**Issue by kajahno** [ricardov03/que-toca#1]
the time shown is being taken from the local system, without considering timezones. This means people from outside Dominican Republic will have different hours for the curfew:
![image](https://user-images.githubusercontent.com/7826376/123517229-cc3eb700-d697-11eb-9054-a54cc9b796b4.png)

**Comment by ricardov03** [comment]
A merge request by @lecollabdul (Hola Karim! y Feliz cumpleaños!) was accepted. I'm pulling the changes to build and deploy with another's changes. @kajahno please check if the time if shows right with those changes. I'll be waiting for your comments before closing this issue. Thanks, both of you guys!

**Comment by kajahno** [comment]
cheers, LGTM! 

![image](https://user-images.githubusercontent.com/7826376/123541864-707b3900-d73e-11eb-998a-6bdeb741d8ec.png)

**Comment by ricardov03** [comment]
Thanks, bro for confirming and close the issue. I'm looking for a comment you sent about how to test this kind of issue. I will comment on there.

**Comment by lecollabdul** [comment]
> 
> 
> A merge request by @lecollabdul (Hola Karim! y Feliz cumpleaños!) was accepted. I'm pulling the changes to build and deploy with another's changes. @kajahno please check if the time if shows right with those changes. I'll be waiting for your comments before closing this issue. Thanks, both of you guys!

Hola Ricardo Gracias!

Excelente!
